#!/bin/bash

#add the home directory of Java to hadoop-env.sh config file
cd /home/hadoopuser/hadoop/bin
JAVA_HOME1=`java JavaHomeDirectory`
echo "export JAVA_HOME=$JAVA_HOME1" >> /home/hadoopuser/hadoop/conf/hadoop-env.sh
echo "export HADOOP_HOME=/home/hadoopuser/hadoop" >> /home/hadoopuser/.bashrc
